class ExError : Exception



func main() {
	throw ExError("s")
}
